env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  simple-import-sort/imports:
    - error
  simple-import-sort/exports:
    - error
  comma-dangle:
    - error
    - always-multiline
